definitions:
  main.FailureError:
    properties:
      error:
        type: string
    type: object
  main.LoginUserSuccess:
    properties:
      message:
        type: string
      token:
        type: string
    type: object
  pb.LoginUserRequest:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a token
      parameters:
      - description: Login Request
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/pb.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.LoginUserSuccess'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.FailureError'
      summary: Login User
      tags:
      - Auth
swagger: "2.0"
